// const financial_advisor = [
//   "price",
//   "worth",
//   "value",
//   "cost",
//   "market",
//   "trade",
//   "swap",
//   "exchange",
//   "convert",
//   "yield",
//   "earn",
//   "apy",
//   "farm",
//   "interest",
//   "risk",
//   "safe",
//   "protect",
//   "secure",
//   "worried",
//   "what",
//   "suggest",
//   "recommend",
//   "should",
//   "advice",
// ];
// const data_scientist = [
//   "volume",
//   "trading",
//   "liquidity",
//   "flows",
//   "volatility",
//   "stable",
//   "movement",
//   "price",
//   "value",
//   "worth",
//   "correlation",
//   "relationship",
//   "compare",
//   "analysis",
//   "metrics",
//   "data",
// ];
// const news_aggregator = [
//   "whale",
//   "large",
//   "transfer",
//   "impact",
//   "affect",
//   "result",
//   "exchange",
//   "platform",
//   "cex",
//   "analysis",
//   "metrics",
//   "news",
// ];
// const patternDetectorBuzzWords = [
//   "volume",
//   "trading",
//   "activity",
//   "volatility",
//   "movement",
//   "swing",
//   "trend",
//   "direction",
//   "moving",
//   "pattern",
//   "metrics",
//   "analysis",
// ];
// const personal_accountant = [
//   // Balance-related triggers
//   "balance",
//   "holding",
//   "have",
//   "own",
//   "worth",
//   "portfolio",
//   "check balance",
//   "asset balance",
//   "check holdings",

//   "send",
//   "transfer",
//   "move",
//   "give",
//   "fund",
//   "allocate",
//   "transfer funds",
//   "send funds",
//   "fund transfer",

//   "approve",
//   "revoke",
//   "allow",
//   "permission",
//   "access",
//   "agent approval",
//   "approve agent",
//   "revoke agent",

//   "wallet",
//   "address",
//   "account",
//   "status",
//   "wallet status",

//   "portfolio overview",
//   "view portfolio",
//   "see portfolio",
//   "show portfolio",
//   "financial overview",

//   "nft",
//   "nft balance",
//   "nft holdings",
//   "check nft",
//   "nft collection",

//   "current portfolio",
//   "asset overview",
//   "view balance",
//   "check status",
//   "current holdings",
//   "view assets",
// ];

// const proposalAnalyzerTriggerWords = [
//   "stakeholder",
//   "holder",
//   "whale",
//   "medium",
//   "small",
//   "voting power",
//   "stakeholder analysis",
//   "analyze stakeholders",
//   "voting analysis",

//   "vote",
//   "voting",
//   "voting power",
//   "vote analysis",
//   "voting distribution",
//   "total voting power",
//   "voting statistics",
//   "analyze voting",

//   "impact",
//   "effect",
//   "result",
//   "outcome",
//   "proposal impact",
//   "impact analysis",

//   "proposal analysis",
//   "analyze proposal",
//   "proposal overview",
//   "proposal impact",
//   "general analysis",
//   "analysis overview",

//   "address",
//   "stakeholder address",
//   "wallet address",
//   "analyze address",
//   "check address",

//   "whale category",
//   "medium category",
//   "small category",
//   "stakeholder category",
//   "category breakdown",
// ];
// const sentimentAnalyzerTriggerWords = [
//   // Token-related buzzwords (Assets)
//   "eth",
//   "ethereum",
//   "btc",
//   "bitcoin",
//   "doge",
//   "dogecoin",
//   "pepe",
//   "wow",

//   // Sentiment-related triggers
//   "sentiment",
//   "social sentiment",
//   "community sentiment",
//   "crowd sentiment",
//   "people sentiment",
//   "social media sentiment",
//   "buy sentiment",
//   "sell sentiment",
//   "token sentiment",
//   "market sentiment",
//   "overall sentiment",

//   // Analysis-related triggers
//   "correlation",
//   "price correlation",
//   "sentiment correlation",
//   "price-sentiment relationship",
//   "sentiment vs price",
//   "trend analysis",
//   "meme sentiment",
//   "hype",
//   "viral",
//   "meme coin",
//   "meme token",
//   "community hype",

//   // Trading activity-related triggers
//   "buy volume",
//   "sell volume",
//   "trade volume",
//   "buy sell ratio",
//   "token activity",
//   "market activity",
//   "buy trend",
//   "sell trend",

//   // Price-related triggers
//   "price",
//   "price trend",
//   "price movement",
//   "price direction",
//   "price action",
//   "price correlation",
//   "asset price",

//   // Trend-related triggers
//   "trend",
//   "movement",
//   "direction",
//   "uptrend",
//   "downtrend",
//   "bullish trend",
//   "bearish trend",
//   "trend analysis",
//   "market trend",

//   // Request/Focus-related triggers
//   "track sentiment",
//   "analyze sentiment",
//   "correlate price",
//   "monitor sentiment",
//   "sentiment analysis",
//   "analyze price correlation",
//   "trend monitoring",
//   "price movement analysis",
//   "meme token analysis",
//   "community analysis",
// ];
// const strategyCoordinatorTriggerWords = [
//   "coordinate",
//   "collaborate",
//   "join",
//   "position",
//   "standing",
//   "power",
//   "move",
//   "transfer",
//   "action",
// ];
// const tokenDeployer = [
//   "Token",
//   "Deploy token",
//   "Create token",
//   "Issue token",
//   "New token",
//   "Generate token",
//   "Deploy",
//   "Issue",
//   "Mint",
//   "Generate",
//   "Create",
//   "Name",
//   "Symbol",
//   "Supply",
//   "Initial supply",
//   "Launch",
//   "Smart contract",
//   "Token contract",
//   "Cryptocurrency token",
//   "Blockchain token",
// ];
// const vote_calculator = [
//   "voting power",
//   "governance token",
//   "strategy analysis",
//   "voting strategy",
//   "threshold analysis",
//   "quorum",
//   "supermajority",
//   "majority",
//   "power calculation",
//   "collaboration",
//   "voting blocks",
//   "balance",
//   "token balance",
//   "voting block",
//   "asset capabilities",
//   "total supply",
//   "quorum contribution",
//   "threshold",
//   "special proposals",
//   "standard proposals",
//   "special majority",
//   "raw power",
//   "percentage",
//   "optimal timing",
//   "collaboration needed",
//   "voting patterns",
//   "voting power optimization",
//   "voting focus",
//   "minimum threshold",
//   "voting calculation",
//   "voting insights",
// ];
