import type { Metadata } from "next";
import "@coinbase/onchainkit/styles.css";
import "./globals.css";
import { Press_Start_2P } from "next/font/google";
import { Providers } from "@/lib/provider";

const pixelFont = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pixelFont.variable}`}
      suppressHydrationWarning
    >
      <body className={`${pixelFont.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
